Titanic ML, Decision Tree Fatality Predictor

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
titanic =sns.load_dataset('titanic')
titanic.head(5)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [3]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [4]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

# Change bool to 1 and 0 for `alive` column

In [8]:
titanic['alive'].unique()

array([0., 1.])

In [6]:
titanic['alive'] = titanic['alive'].str.replace('yes','1', regex=True)
titanic['alive'] = titanic['alive'].str.replace('no','0', regex=True)
titanic.head(2)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton     0  False  
1  woman       False    C    Cherbourg     1  False

In [7]:
titanic['alive'] = titanic['alive'].astype(float)

# quirk alert!

In [12]:
titanic['sex'].unique()

array([1., 0.])

In [10]:
titanic['sex'] = titanic['sex'].str.replace('male','1', regex=True)
titanic['sex'] = titanic['sex'].str.replace('female','0', regex=True)
titanic['sex'] = titanic['sex'].str.replace('fe1','0', regex=True)
titanic.head(2)

survived  pclass sex   age  sibsp  parch     fare embarked  class    who  \
0         0       3   1  22.0      1      0   7.2500        S  Third    man   
1         1       1   0  38.0      1      0  71.2833        C  First  woman   

   adult_male deck  embark_town  alive  alone  
0        True  NaN  Southampton    0.0  False  
1       False    C    Cherbourg    1.0  False

In [11]:
titanic['sex'] = titanic['sex'].astype(float)

# Create input set

In [13]:
X = titanic[['sex','fare']]

# Create output set

In [14]:
y = titanic['alive']

# Create Train / Test Split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

# Select and fit the model

In [20]:
model = DecisionTreeClassifier()
model.fit(X_train.values, y_train)

DecisionTreeClassifier()

In [23]:
model.predict([[0,3]])

array([1.])

In [26]:
predictions = model.predict(X_test.values)

In [28]:
score = accuracy_score(y_test, predictions)
score

0.8044692737430168

In [ ]:
# Cool

In [29]:
import joblib 
joblib.dump(model, 'titanic_fatality_predictor.joblib')

['titanic_fatality_predictor.joblib']